apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-settings
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - folder: applications/platform
      - folder: applications/homelab
  template:
    metadata:
      finalizers: []
      name: 'argocd-{{ .folder | replace "/" "-" }}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      source:
        repoURL: ssh://git@github.com/alemuro/infra-homelab-argo.git
        targetRevision: HEAD
        path: '{{ .folder }}'
        directory:
          recurse: true
      destination:
        name: homelab
        namespace: argocd
