apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-settings
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      # - folder: config
      - folder: applications/platform
      # - folder: manifests
  template:
    metadata:
      finalizers: []
        name: 'argocd-{{folder | replace "/" "-"}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
      source:
        repoURL: ssh://git@github.com/alemuro/infra-homelab-argo.git
        targetRevision: HEAD
        path: '{{folder}}'
        directory:
          recurse: true
      destination:
        name: homelab
        namespace: argocd
